### PR TITLE
Add test suite to repo

### PR DESCRIPTION
**Pull request by julesnuggy**
## Objective
Add tests so that we can check students' work using automated tests (via GH Actions).

## What Has Changed?
* Installed & configured Jest
* Use the Prisma Client's `dmff` object to retrieve the locally generated models
* For each model, and at each relevant Requirement stage, write tests to assert:
  * that the expected fields/columns exist
  * that each field has the correct attributes:
```js
  type,
  isId,
  isRequired,
  isUnique,
  defaultValue,
  relationFromFields,
  relationToFields,
  isList,
```

## How To Test
* Run `npm ci`
* Update the `prisma.schema` file to contain the correct models
  * [Example from student (though not everything passes)](https://github.com/lucianosimoni/database-orm-1/blob/main/prisma/schema.prisma)
* To run the tests for a specific requirement, run `npm run test:<number>` where `<number>` is replaced by the relevant digit (e.g. to test Requirement 2, run `npm run test:2`).
* To run all tests, run `npm run test:all`.

### CODE REVIEW

**Comment by julesnuggy** [comment]
@vherus -- I knew I forgot to do something, but couldn't remember what! 🙈  Good shout!

**Review by vherus — APPROVED** [review]

**Review by dearshrewdwit — CHANGES_REQUESTED** [review]
Great stuff.

Can you standardise the CI test scripts and actions?

Follow the format below: 
- all exercises should have at least the defiend standard criteria testable with a workflow and corresponding test suite.
- If there are defined extension criteria, there should be a separate workflow with a corresponding test suite.

Example: https://github.com/boolean-uk/api-express-database/tree/main/.github/workflows

If you want to define extra test scripts - feel free to do so, beyond the above standardised ones.

**Comment by julesnuggy** [comment]
@dearshrewdwit -- thanks for the review. I've addressed your comment (I believe). There are no extensions, just the standard, so I've updated the workflow filename & action name, and also updated the npm script name.

**Review by dearshrewdwit — APPROVED** [review]
Nice. Let's get it merged

**Pull request merged**
